---
- name: capture hosts for non-production policy
  hosts: non_production
  gather_facts: yes
  tasks:
    - name: create non_production policy host list
      template:
        src: templates/non_prod_host_file_template.j2
        dest: files/non_prod_hosts
      delegate_to: localhost
        
    - name: display file content
      set_stats:
        data:
          file_contents: "{{ item }}"
      with_file:
        - "files/non_prod_hosts"
      delegate_to: localhost

- name: capture hosts for production policy
  hosts: production
  gather_facts: yes
  tasks:    
    - name: create production policy host list
      template:
        src: templates/prod_host_file_template.j2
        dest: files/prod_hosts
      delegate_to: localhost
        
    - name: display file content
      set_fact:
        file_contents: "{{ item }}"
      with_file:
        - "files/prod_hosts"
      delegate_to: localhost
    

