---
- name: Run insights compliance scan
  hosts: all
  become: true

  tasks:
    - name: Ensure the packages required are installed
      yum:
        name:
          - scap-security-guide
          - openscap-scanner
          - openscap
        state: present

    - name: Run insights compliance
      import_role:
        name: redhat.insights.compliance
        tasks_from: run
