---

- name: capture hosts adding to compliance policies
  hosts: label_compliance_policy_standard 
  gather_facts: yes
#  remote_user: cloud-user
  vars_files:
    - secrets_folder/ovirt-pass 

  tasks:
 
    - name: create standard policy host list
      template:
        src: templates/STD_host_file_template.j2
        dest: files/std_compliance_hosts-1
      delegate_to: localhost
      vars:
        ansible_connection: local
#      when: compliance_type == 'label_compliance_policy_standard' 


#    - name: create pci policy host list
#      template:
#        src: templates/PCI_host_file_template.j2
#        dest: files/pci_compliance_hosts
#      delegate_to: localhost
#      when: compliance_type == 'label_compliance_policy_pci'



- name: add host to compliance policies
  hosts: localhost
  vars:
    ansible_connection: local
  gather_facts: no
#  vars:
#    - profile_name: 'Protection Profile for General Purpose Operating Systems'
#    - host_name: '2021-09-03-20-41-06-1.dumont-lab.lan'
  vars_files:
    - secrets_folder/ovirt-pass
#    - vars/test_vars.yml


  tasks:
    - name: get access token
      uri:
        url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
        method: POST
        return_content: True
        body_format: form-urlencoded
        headers:
    #          Content-Type: "application/json"
          accept: application/json
        body:
          grant_type: refresh_token
          client_id: rhsm-api
          refresh_token: "{{ my_offline_token }}"
    #        force_basic_auth: True
        validate_certs: False
      register: access_token_reponse

    - name: print access token
      set_fact:
        token: "{{ access_token_reponse.json.access_token }}"



    - name: Get Compliance List-URI
      uri:
        url: https://console.redhat.com/api/compliance/profiles
        method: GET
        headers:
          Authorization: "Bearer {{ token }}"        
          Content-Type: "application/json"
          accept: application/json
        body_format: form-urlencoded
        status_code: 200
        return_content: yes
        validate_certs: false
        force_basic_auth: yes
      register: profiles
      delegate_to: localhost

    - name: set profile list
      set_fact:
        profile_list: "{{ profiles.json }}"

    - name: profile_id
      set_fact:
#        profile_id: "{{ profile_list | json_query(get_profile_id) }}"
        profile_id: "{{ profile_list | json_query(get_profile_id) }}"        
      vars:
#        get_profile_id: "{{ \"data[?attributes.name == 'Protection Profile for General Purpose Operating Systems'].id\" }}"
        get_profile_id: "data[?attributes.name ==  '{{ profile_name }}'].id"

    - name: Get Host List
      uri:
        url: https://cloud.redhat.com/api/inventory/v1/hosts
        method: GET                                                                                                                                 
        headers:
          Authorization: "Bearer {{ token }}"
          Content-Type: "application/json"
          accept: application/json
        body_format: form-urlencoded
        status_code: 200
        return_content: yes
        validate_certs: false
        force_basic_auth: yes
      register: host_list

    - name: host_data fact
      set_fact:
        host_data: "{{ host_list.json }}"


    - name: print fact
      debug:
        var: host_data


    - name: set file content fact to std
      set_fact:
        file_contents: "{{ item }}"
      with_file:
        - "files/std_compliance_hosts-1"
      delegate_to: localhost
#      when: compliance_type == 'label_compliance_policy_standard'

    - name: print file content fact
      debug:
        var: file_contents


#    - name: set file content fact to pci                     
#      set_fact:                                             
#        file_contents: "{{ item }}"                         
#      with_file:                                            
#        - "files/pci_compliance_hosts"                      
#      delegate_to: localhost                                
#      when: compliance_type == 'label_compliance_policy_pci'




    - name: get uuid of host
      set_fact:
        uuid: "{{ uuid + [ host_data | json_query(get_uuid)] }}"
      vars:
        uuid: []
        get_uuid: "results[?fqdn == '{{ item }}'].id"
#      loop: "{{ file_contents | split(',') }}"
      loop: "{{ file_contents | split('\n') }}"
#      loop: "{{ file_contents }}"
      delegate_to: localhost

    - name: print uuid
      debug:
        var: uuid                                                              
 
    - name: create lookup file
      template:
        src=templates/compliance_host.j2
        dest=compliance_host.json
        mode=0644
      delegate_to: localhost
    
    - name: lookup compliance host
      set_fact:
        json_file: "{{ lookup('file', 'compliance_host.json') }}"
    
    - name: print var
      debug:
        var=json_file

    - name: Update Compliance Host List
      uri:
        url: "https://cloud.redhat.com/api/compliance/profiles/{{ profile_id[0] }}"
        method: PATCH
#        method: GET
        headers:
          Authorization: "Bearer {{ token }}"
          Content-Type: "application/json"
          accept: application/json
        body_format: json
        body: "{{ lookup('file','compliance_host.json') }}"
        status_code: 200
        return_content: yes
        validate_certs: false
        force_basic_auth: yes
      register: new_profile

