---
- name: Capture hosts for {{ hosts }} policy #{{ hosts }}
  hosts: {{ hosts }} # {{ hosts }}
  gather_facts: yes
  tasks:    
    - name: Create {{ hosts }} policy host list #{{ hosts }}
      template:
        src: templates/{{ hosts }}_host_file_template.j2 #{{ hosts }}
        dest: files/{{ hosts }}_hosts #{{ hosts }}
      delegate_to: localhost
        
    - name: Display file content
      set_fact:
        file_contents: "{{ item }}"
      with_file:
        - "files/{{ hosts }}_hosts" # {{ hosts }}
      delegate_to: localhost

- name: Add hosts to compliance policies
  hosts: {{ hosts }} # {{ hosts }}
  vars:
    - ansible_connection: local
    - profile_name: {{ profile_name }} # {{ profile_name }}
  gather_facts: no

  tasks:
    - name: Get access token
      uri:
        url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
        method: POST
        return_content: True
        body_format: form-urlencoded
        headers:
          accept: application/json
        body:
          grant_type: refresh_token
          client_id: rhsm-api
          refresh_token: "{{ my_offline_token }}"
        validate_certs: False
      register: access_token_reponse

    - name: Print access token
      set_fact:
        token: "{{ access_token_reponse.json.access_token }}"

    - name: Get list of compliance profiles from the Red Hat Insights API
      uri:
        url: https://console.redhat.com/api/compliance/profiles
        method: GET
        headers:
          Authorization: "Bearer {{ token }}"        
          Content-Type: "application/json"
          accept: application/json
        body_format: form-urlencoded
        status_code: 200
        return_content: yes
        validate_certs: false
        force_basic_auth: yes
      register: profiles
      delegate_to: localhost

    - name: Set profile list
      set_fact:
        profile_list: "{{ profiles.json }}"

    - name: Set profile_id
      set_fact:
        profile_id: "{{ profile_list | json_query(get_profile_id) }}"        
      vars:
        get_profile_id: "data[?attributes.name ==  '{{ profile_name }}'].id"

    - name: Get list of hosts from the Red Hat Insights API
      uri:
        url: https://cloud.redhat.com/api/inventory/v1/hosts
        method: GET                                                       
        headers:
          Authorization: "Bearer {{ token }}"
          Content-Type: "application/json"
          accept: application/json
        body_format: form-urlencoded
        status_code: 200
        return_content: yes
        validate_certs: false
        force_basic_auth: yes
      register: host_list

    - name: Set host_data fact
      set_fact:
        host_data: "{{ host_list.json }}"

    - name: Print fact
      debug:
        var: host_data

    - name: Set file content to host_data fact                     
      set_fact:                                             
        file_contents: "{{ item }}"                         
      with_file:                                            
        - "files/{{ hosts }}_hosts" # {{ hosts }}               
      delegate_to: localhost                                

    - name: Print file content fact
      debug:
        var: file_contents

    - name: Get uuid of each of the hosts
      set_fact:
        uuid: "{{ uuid + [ host_data | json_query(get_uuid)] }}"
      vars:
        uuid: []
        get_uuid: "results[?fqdn == '{{ item }}'].id"
      loop: "{{ file_contents | split('\n') }}"
      delegate_to: localhost

    - name: print uuid
      debug:
        var: uuid                                                              
    - name: create lookup file
      template:
        src=templates/compliance_host.j2
        dest=compliance_host.json
        mode=0644
      delegate_to: localhost
    
    - name: Lookup compliance host
      set_fact:
        json_file: "{{ lookup('file', 'compliance_host.json') }}"
    
    - name: Print var
      debug:
        var=json_file

    - name: Update the OpenSCAP policy with the relevant hosts
      uri:
        url: "https://console.redhat.com/api/compliance/profiles/{{ profile_id[0] }}"
        method: PATCH
        headers:
          Authorization: "Bearer {{ token }}"
          Content-Type: "application/json"
          accept: application/json
        body_format: json
        body: "{{ lookup('file','compliance_host.json') }}"
        status_code: 200
        return_content: yes
        validate_certs: false
        force_basic_auth: yes
      register: new_profile
      ignore_errors: yes