---
- name: add host to compliance policies
  hosts: all
  vars:
    - ansible_connection: local
  gather_facts: no

  tasks:
    - name: get access token
      uri:
        url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
        method: POST
        return_content: True
        body_format: form-urlencoded
        headers:
          accept: application/json
        body:
          grant_type: refresh_token
          client_id: rhsm-api
          refresh_token: "{{ my_offline_token }}"
        validate_certs: False
      register: access_token_reponse

    - name: print access token
      set_fact:
        token: "{{ access_token_reponse.json.access_token }}"

    - name: Include looped tasks
      include_tasks: looped_tasks.yml
      loop: [1, 2, 3, 4]
