---
- name: Register to subscription manager & auto attach relevant subscription
  hosts: all
  become: true
  tasks:
    - name: Register with my username
      community.general.redhat_subscription:
        state: present
        username: "{{ username }}"
        password: "{{ password }}"
        pool_ids: "{{ pool_ids }}"
